package(default_testonly = 1)

java_test(
    name = "CustomValueTypeTest",
    srcs = ["CustomValueTypeTest.java"],
    deps = [
        "//java/musubi",
        "//java/musubi/testing",
        "//third_party/junit4",
    ],
)
