# Shared utilities used for testing

package(default_visibility = ["//visibility:public"])

java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    deps = [
        "//java/musubi:musubi",
        "//third_party/junit4",
    ],
)
